# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)


In [3]:
import torch
scalar =torch.tensor(7)
print(scalar)
#get tesnor back to int
scalar.item()

tensor(7)


7

In [7]:
import torch
vector = torch.tensor([7,7])
print(vector)
vector.shape
#gives the elements occupied by the vector

tensor([7, 7])


torch.Size([2])

In [10]:
#mactrix
matrix=torch.tensor([[7,8,],[9,10]])
print(matrix)
matrix.ndim
matrix[0]

tensor([[ 7,  8],
        [ 9, 10]])


tensor([7, 8])

In [16]:
matrix=torch.tensor([[[7,8,],[9,10],[5,6]]])
print(matrix)
matrix.ndim
matrix.shape
#gice a lower case for scalar and vector
#upper for matrix and tensor
#random tenssors are important...neurals networks learn is that start with randoms tynsros
#then adjust the tensors

tensor([[[ 7,  8],
         [ 9, 10],
         [ 5,  6]]])


torch.Size([1, 3, 2])

In [19]:
random_tensor=torch.rand(10,10,10)
random_tensor
random_tensor.ndim


3

In [20]:
random_image_size_tensor=torch.rand(size=(224,224,3))#height,width,colour channel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
##zeros or ones
zero=torch.zeros(size=(3,4))
print(zero)
ones=torch.ones(size=(3,4))
print(ones)
ones.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.float32

In [26]:
#use torch range
a=torch.arange(0,12,4)
print(a)

tensor([0, 4, 8])


In [4]:
import torch

b = torch.tensor([1.0, 2.0, 3.0],
                 dtype=None,
                 device=None,
                 requires_grad=False)  # Creating a tensor with float values
b
f                # Prints the data type of the tensor



tensor([1., 2., 3.])

In [7]:
#manipulating tensors
tensor=torch.tensor([1,2,3])
print(tensor+10)
print(tensor*10)
print(tensor-10)
print(tensor/10)




tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [8]:
##two main ways to save matric multiplication
1#.element wise
#2.matrix multiplication(dot.product)
print(tensor*tensor)
print(f"euals:{tensor*tensor}")


tensor([1, 4, 9])
euals:tensor([1, 4, 9])


In [9]:
torch.matmul(tensor,tensor)

tensor(14)

In [10]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)).shape

torch.Size([3, 3])

In [12]:
matrix1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
matrix2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

result = torch.mm(matrix1, matrix2)  # or use: result = matrix1 @ matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result)

Matrix 1:
tensor([[1., 2.],
        [3., 4.]])

Matrix 2:
tensor([[5., 6.],
        [7., 8.]])

Result of Matrix Multiplication:
tensor([[19., 22.],
        [43., 50.]])


In [13]:
import torch

# Define a matrix
b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

# Transpose the matrix
#b_transposed = torch.t(b)  # Method 1: Using torch.t()
# or
b_transposed = b.T         # Method 2: Using the .T attribute

# Print original and transposed matrices
print("Original Matrix:")
print(b)

print("\nTransposed Matrix:")
print(b_transposed)


Original Matrix:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Transposed Matrix:
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


#gice a lower case for scalar and vector
#upper for matrix and tensor
#random tenssors are important...neurals networks learn is that start with randoms tynsros
#then adjust the tensors

In [17]:
import torch

# Define a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

tensor_min = torch.min(tensor)     # Minimum value
tensor_max = torch.max(tensor)     # Maximum value
tensor_mean = torch.mean(tensor)   # Mean value
tensor_sum = torch.sum(tensor)     # Sum of all elements


print("Tensor:"f)
print(tensor)

print("\nMinimum Value:", tensor_min.item())
print("Maximum Value:", tensor_max.item())
print("Mean Value:", tensor_mean.item())
print("Sum of Elements:", tensor_sum.item())
tensor.argmin()#finds the pos of minimum value
tensor.argmax()#find the pos of maxvalue




Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Minimum Value: 1.0
Maximum Value: 6.0
Mean Value: 3.5
Sum of Elements: 21.0


tensor(0)

In [22]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))